### ISSUE TITLE
Chokidar not watching file changes if filename is 12_maps.js

### ISSUE THREAD

**Issue by alayek** [kentcdodds/es6-workshop#33] opened 2017-01-10 18:36 UTC
When running the command `yarn quiz` or `npm run quiz`, it's rerunning only on the first file change for this file.

After that, it's been ignoring all file changes on the file. However, changes in other files detected
And this is happening only for one file, `12_maps.js`.

I tested the chokidar regex from `run.js`, which is `*_*.js` under `quizzes` directory.

I tested on two machines. On my laptop, I faced same issue with Atom and VSCode embedded terminals.

I have reproduced the issue on Cloud9. You can view the issue live [here](https://ide.c9.io/alayek/es6-workshop).

Have also posted in the gitter chatroom.

**Comment by kentcdodds** [comment] 2017-01-20 23:16
Hmmm.. I was unable to reproduce this myself... If you would like to dig deeper into it and come up with a solution, feel free. Otherwise I'll go ahead and close this as the impact on workshop attendees is minimal. Thanks!

**Closed as completed by kentcdodds** 2017-01-20 23:16 UTC
